function cellInfo = Geskf_Res (varargin)
%ElementName,Dimensions,DataType,SampleTime,Complexity,SamplingMode,DimensionMode,Min,Max,DocUnits,Description
cellInfo = {
        {'Geskf_Res','','','Auto','-1',{...
                {'timestamp',1,'uint64',-1,'real','Sample','Fixed',[],[],'','时间戳，随着运行时间增加'};...
                {'euler_rad',[3 1],'single',-1,'real','Sample','Fixed',[],[],'rad','欧拉角'};...
                {'euler_rate_radPs',[3 1],'single',-1,'real','Sample','Fixed',[],[],'rad/s','欧拉角速率'};...
                {'quaternion',[4 1],'single',-1,'real','Sample','Fixed',[],[],'','姿态四元数'};...
                {'velocity_N_mPs',[3 1],'single',-1,'real','Sample','Fixed',[],[],'','地理系下速度'};...
                {'position_N_m',[3 1],'single',-1,'real','Sample','Fixed',[],[],'','地理系下位置'};... 
                {'delta_ang_bias',[3 1],'single',-1,'real','Sample','Fixed',[],[],'','角度差漂移'};... 
                {'delta_vel_bias',[3 1],'single',-1,'real','Sample','Fixed',[],[],'','速度差漂移'};... 
                
            }...
        }...
    }';
Simulink.Bus.cellToObject(cellInfo);


    