function res = getNumberOfActiveHorizontalAidingSources()
    global control_status;
    res = control_status.flags.gps...
	       + control_status.flags.opt_flow...
	       + control_status.flags.ev_pos...
	       + control_status.flags.ev_vel...     
	       + (control_status.flags.fuse_aspd && control_status.flags.fuse_beta);

end